# Generated by Django 3.0.6 on 2020-05-16 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20200515_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theblog.Post')),
            ],
            options={
                'db_table': 'ArticleStatistic',
            },
        ),
    ]
