# Generated by Django 3.0.6 on 2020-05-24 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0012_auto_20200523_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ok',
            field=models.ManyToManyField(related_name='ok_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
