# Generated by Django 3.0.6 on 2020-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_post_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Python', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=models.CharField(max_length=120), max_length=120),
        ),
    ]
