# Generated by Django 3.0.6 on 2020-06-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_comment_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ok',
        ),
    ]
