# Generated by Django 3.0.6 on 2020-06-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_auto_20200628_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='author',
        ),
    ]
