# Generated by Django 3.0.6 on 2020-06-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_auto_20200628_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
